baseURL = "https://themes.gohugo.io"
title = "Hugo Themes"
#author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
paginate = 3

[blackfriday]
plainIdAnchors=true
